INSERT INTO categoria VALUE (1, 'Base de datos' );
INSERT INTO categoria VALUE (2, 'Programacion' );
INSERT INTO categoria VALUE (3, 'Redes' );
INSERT INTO categoria VALUE (4, 'Ofimatica' );
INSERT INTO categoria VALUE (5, 'Hardware' );
INSERT INTO categoria VALUE (6, 'Seguridad' );
INSERT INTO categoria VALUE (7, 'Aplicaciones Web' );
INSERT INTO categoria VALUE (8, 'Sistemas Operativos' );
INSERT INTO categoria VALUE (9, 'Miscelanea' );
INSERT INTO libro VALUES (4,'Santa Tecla','Pepito','Editorial 1',3);
INSERT INTO libro VALUES (5,'Programando Bots','Pepito','Editorial 3',2);
INSERT INTO libro VALUES (6,'Terminator','Paquito','Editorial 1',5);
INSERT INTO libro VALUES (7,'WebOS','Andreita','Editorial 3',7);
INSERT INTO libro VALUES (8,'Santa Tecla Returns','Pepito','Editorial 1',8);
INSERT INTO libro VALUES (9,'Buceando en SQLite','Pepito','Editorial 2',1);
INSERT INTO libro VALUES (10,'Windows (Keylogger) 10','Paquito','Editorial 2',8);
INSERT INTO libro VALUES (11,'He perdido las llaves','Andreita','Editorial 1',6);
INSERT INTO libro VALUES (12,'Sin RETURN','Pedrolo','Editorial 67',2);
INSERT INTO libro VALUES (13,'Pruebas','Pedrolo','Editorial 67',2);
INSERT INTO usuario VALUES (1,'Antonio','Flores');
INSERT INTO usuario VALUES (2,'Maria','Andújar');
INSERT INTO usuario VALUES (3,'Rocio','Olvido');
INSERT INTO usuario VALUES (4,'Julian','Cateto');
INSERT INTO usuario VALUES (5,'Pepe','López');
INSERT INTO prestamos VALUES (1,4,2,'2021-04-17 18:02:50');
INSERT INTO prestamos VALUES (3,6,4,'2021-03-10 10:02:55');
INSERT INTO prestamos VALUES (4,7,5,'2021-04-17 18:02:50');